import type { WorkflowDefinition } from "../core/types.js";

export const workflowCatalog: WorkflowDefinition[] = [
  {
    id: "build-product",
    name: "Build Product",
    goal: "Turn a new product idea into a tested implementation.",
    summary: "Repo-backed build workflow from opportunity analysis to verification.",
    steps: [
      {
        id: "idea-analysis",
        agentId: "ceo-agent",
        ownerRole: "ceo",
        skillId: "opportunity-analysis",
        skillIds: ["opportunity-analysis"],
        output: "opportunity-summary",
        produces: ["opportunity-summary"],
      },
      {
        id: "product-design",
        agentId: "product-agent",
        ownerRole: "product-manager",
        skillId: "prd-generation",
        skillIds: ["prd-generation"],
        output: "prd",
        produces: ["prd"],
      },
      {
        id: "architecture",
        agentId: "architect-agent",
        ownerRole: "architect",
        skillId: "system-architecture",
        skillIds: ["system-architecture"],
        output: "architecture-blueprint",
        produces: ["architecture-blueprint"],
      },
      {
        id: "development",
        agentId: "engineer-agent",
        ownerRole: "engineer",
        skillId: "code-generation",
        skillIds: ["code-generation"],
        output: "implementation",
        produces: ["implementation"],
      },
      {
        id: "testing",
        agentId: "qa-agent",
        ownerRole: "qa",
        skillId: "integration-test",
        skillIds: ["integration-test"],
        output: "verification-report",
        produces: ["verification-report"],
      },
    ],
  },
  {
    id: "ship-feature",
    name: "Ship Feature",
    goal: "Deliver a scoped feature into an existing product.",
    summary: "Repo-backed feature delivery workflow.",
    steps: [
      {
        id: "ship-feature-1",
        agentId: "product-agent",
        ownerRole: "product-manager",
        skillId: "feature-prioritization",
        skillIds: ["feature-prioritization"],
        output: "feature-prioritization-result",
        produces: ["feature-prioritization-result"],
      },
      {
        id: "ship-feature-2",
        agentId: "architect-agent",
        ownerRole: "architect",
        skillId: "api-design",
        skillIds: ["api-design"],
        output: "api-design-result",
        produces: ["api-design-result"],
      },
      {
        id: "ship-feature-3",
        agentId: "engineer-agent",
        ownerRole: "engineer",
        skillId: "code-generation",
        skillIds: ["code-generation"],
        output: "implementation",
        produces: ["implementation"],
      },
      {
        id: "ship-feature-4",
        agentId: "qa-agent",
        ownerRole: "qa",
        skillId: "unit-test",
        skillIds: ["unit-test"],
        output: "unit-test-result",
        produces: ["unit-test-result"],
      },
    ],
  },
  {
    id: "fix-bug",
    name: "Fix Bug",
    goal: "Diagnose and resolve a product defect.",
    summary: "Repo-backed defect triage, design, implementation, and verification workflow.",
    steps: [
      {
        id: "fix-bug-1",
        agentId: "qa-agent",
        ownerRole: "qa",
        skillId: "bug-analysis",
        skillIds: ["bug-analysis"],
        output: "bug-analysis-result",
        produces: ["bug-analysis-result"],
      },
      {
        id: "fix-bug-2",
        agentId: "architect-agent",
        ownerRole: "architect",
        skillId: "system-architecture",
        skillIds: ["system-architecture"],
        output: "architecture-blueprint",
        produces: ["architecture-blueprint"],
      },
      {
        id: "fix-bug-3",
        agentId: "engineer-agent",
        ownerRole: "engineer",
        skillId: "code-generation",
        skillIds: ["code-generation"],
        output: "implementation",
        produces: ["implementation"],
      },
      {
        id: "fix-bug-4",
        agentId: "qa-agent",
        ownerRole: "qa",
        skillId: "integration-test",
        skillIds: ["integration-test"],
        output: "verification-report",
        produces: ["verification-report"],
      },
    ],
  },
];
