import {
  bulletList,
  section,
  summarizePreviousResults,
  withHeader,
} from "./shared.mjs";

export const id = "fallback";

export function render(context) {
  return [
    ...withHeader(context),
    section("Skill Definition", [
      "Inputs:",
      bulletList(context.skill.inputs),
      "",
      "Outputs:",
      bulletList(context.skill.outputs),
    ]),
    section("Execution Context", [
      `Idea: ${context.idea}`,
      "This artifact was generated by the template fallback path.",
    ]),
    section("Previous Artifacts", summarizePreviousResults(context.previousResults).map((item) => `- ${item}`)),
  ].join("\n");
}
