import type { SkillPackage } from "../core/skill-engine/types.js";

const manualAndWorkflow = ["manual", "workflow_step"] as const;

export const skillCatalog: SkillPackage[] = [
  {
    id: "opportunity-analysis",
    namespace: "startup-os",
    name: "Opportunity Analysis",
    description: "Evaluate market need, constraints, and strategic fit.",
    category: "strategy",
    entrypoint: "skills/thinking/opportunity-analysis.md",
    assets: ["skills/thinking/opportunity-analysis.md"],
    triggerSources: [...manualAndWorkflow],
    requiresCapabilities: [],
    dependsOnSkills: [],
    fallbackSkills: [],
  },
  {
    id: "strategy-design",
    namespace: "startup-os",
    name: "Strategy Design",
    description: "Shape product and company strategy from a validated opportunity.",
    category: "strategy",
    entrypoint: "skills/thinking/strategy-design.md",
    assets: ["skills/thinking/strategy-design.md"],
    triggerSources: [...manualAndWorkflow],
    requiresCapabilities: [],
    dependsOnSkills: ["opportunity-analysis"],
    fallbackSkills: [],
  },
  {
    id: "feature-prioritization",
    namespace: "startup-os",
    name: "Feature Prioritization",
    description: "Turn product opportunities into prioritized delivery scope.",
    category: "planning",
    entrypoint: "skills/product/feature-prioritization.md",
    assets: ["skills/product/feature-prioritization.md"],
    triggerSources: [...manualAndWorkflow],
    requiresCapabilities: [],
    dependsOnSkills: ["opportunity-analysis"],
    fallbackSkills: [],
  },
  {
    id: "prd-generation",
    namespace: "startup-os",
    name: "PRD Generation",
    description: "Produce a product requirements document from validated context.",
    category: "planning",
    entrypoint: "skills/product/prd-generation.md",
    assets: ["skills/product/prd-generation.md"],
    triggerSources: [...manualAndWorkflow],
    requiresCapabilities: [],
    dependsOnSkills: ["opportunity-analysis"],
    fallbackSkills: [],
  },
  {
    id: "user-journey",
    namespace: "startup-os",
    name: "User Journey",
    description: "Map user flow and lifecycle experience across core product paths.",
    category: "planning",
    entrypoint: "skills/product/user-journey.md",
    assets: ["skills/product/user-journey.md"],
    triggerSources: [...manualAndWorkflow],
    requiresCapabilities: [],
    dependsOnSkills: ["prd-generation"],
    fallbackSkills: [],
  },
  {
    id: "system-architecture",
    namespace: "startup-os",
    name: "System Architecture",
    description: "Define service boundaries, interfaces, and architecture slices.",
    category: "design",
    entrypoint: "skills/engineering/system-architecture.md",
    assets: ["skills/engineering/system-architecture.md"],
    triggerSources: [...manualAndWorkflow],
    requiresCapabilities: [],
    dependsOnSkills: ["prd-generation"],
    fallbackSkills: [],
  },
  {
    id: "api-design",
    namespace: "startup-os",
    name: "API Design",
    description: "Specify service contracts and external-facing interfaces.",
    category: "design",
    entrypoint: "skills/engineering/api-design.md",
    assets: ["skills/engineering/api-design.md"],
    triggerSources: [...manualAndWorkflow],
    requiresCapabilities: [],
    dependsOnSkills: ["system-architecture"],
    fallbackSkills: [],
  },
  {
    id: "database-design",
    namespace: "startup-os",
    name: "Database Design",
    description: "Define storage models and persistence boundaries.",
    category: "design",
    entrypoint: "skills/engineering/database-design.md",
    assets: ["skills/engineering/database-design.md"],
    triggerSources: [...manualAndWorkflow],
    requiresCapabilities: [],
    dependsOnSkills: ["system-architecture"],
    fallbackSkills: [],
  },
  {
    id: "code-generation",
    namespace: "startup-os",
    name: "Code Generation",
    description: "Produce a concrete implementation slice for the selected workflow.",
    category: "implementation",
    entrypoint: "skills/engineering/code-generation.md",
    assets: ["skills/engineering/code-generation.md"],
    triggerSources: ["task_assigned", "workflow_step"],
    requiresCapabilities: [],
    dependsOnSkills: ["system-architecture"],
    fallbackSkills: [],
  },
  {
    id: "unit-test",
    namespace: "startup-os",
    name: "Unit Test",
    description: "Define unit-level verification scope and checks.",
    category: "verification",
    entrypoint: "skills/testing/unit-test.md",
    assets: ["skills/testing/unit-test.md"],
    triggerSources: ["task_assigned", "workflow_step"],
    requiresCapabilities: [],
    dependsOnSkills: ["code-generation"],
    fallbackSkills: [],
  },
  {
    id: "integration-test",
    namespace: "startup-os",
    name: "Integration Test",
    description: "Validate end-to-end coherence across produced artifacts.",
    category: "verification",
    entrypoint: "skills/testing/integration-test.md",
    assets: ["skills/testing/integration-test.md"],
    triggerSources: ["task_assigned", "workflow_step"],
    requiresCapabilities: [],
    dependsOnSkills: ["code-generation"],
    fallbackSkills: ["unit-test"],
  },
  {
    id: "bug-analysis",
    namespace: "startup-os",
    name: "Bug Analysis",
    description: "Diagnose defects and constrain the fix path.",
    category: "verification",
    entrypoint: "skills/testing/bug-analysis.md",
    assets: ["skills/testing/bug-analysis.md"],
    triggerSources: ["task_assigned", "workflow_step", "manual"],
    requiresCapabilities: [],
    dependsOnSkills: [],
    fallbackSkills: [],
  },
  {
    id: "marketing-strategy",
    namespace: "startup-os",
    name: "Marketing Strategy",
    description: "Shape go-to-market strategy around the current product direction.",
    category: "strategy",
    entrypoint: "skills/growth/marketing-strategy.md",
    assets: ["skills/growth/marketing-strategy.md"],
    triggerSources: [...manualAndWorkflow],
    requiresCapabilities: [],
    dependsOnSkills: ["opportunity-analysis"],
    fallbackSkills: [],
  },
  {
    id: "saas-pricing",
    namespace: "startup-os",
    name: "SaaS Pricing",
    description: "Design pricing and packaging assumptions for SaaS products.",
    category: "strategy",
    entrypoint: "skills/growth/saas-pricing.md",
    assets: ["skills/growth/saas-pricing.md"],
    triggerSources: [...manualAndWorkflow],
    requiresCapabilities: [],
    dependsOnSkills: ["marketing-strategy"],
    fallbackSkills: [],
  },
];
