import type { AgentDefinition } from "../core/types.js";

export const agentCatalog: AgentDefinition[] = [
  {
    id: "ceo-agent",
    role: "ceo",
    name: "CEO Agent",
    title: "CEO Agent",
    mission: "Turn company goals into execution strategy.",
    capabilities: ["strategy", "prioritization", "coordination"],
    defaultSkillIds: ["opportunity-analysis", "strategy-design", "feature-prioritization"],
  },
  {
    id: "product-agent",
    role: "product-manager",
    name: "Product Agent",
    title: "Product Agent",
    mission: "Convert ideas into product requirements and roadmap decisions.",
    reportsTo: "ceo-agent",
    capabilities: ["prd", "prioritization", "user journeys"],
    defaultSkillIds: ["prd-generation", "feature-prioritization", "user-journey"],
  },
  {
    id: "architect-agent",
    role: "architect",
    name: "Architect Agent",
    title: "Architect Agent",
    mission: "Design systems, interfaces, and technical boundaries.",
    reportsTo: "ceo-agent",
    capabilities: ["architecture", "api design", "database design"],
    defaultSkillIds: ["system-architecture", "api-design", "database-design"],
  },
  {
    id: "engineer-agent",
    role: "engineer",
    name: "Engineer Agent",
    title: "Engineer Agent",
    mission: "Implement product features and internal systems.",
    reportsTo: "architect-agent",
    capabilities: ["implementation", "delivery", "bug analysis"],
    defaultSkillIds: ["code-generation", "api-design", "bug-analysis"],
  },
  {
    id: "qa-agent",
    role: "qa",
    name: "QA Agent",
    title: "QA Agent",
    mission: "Validate delivery quality and protect release confidence.",
    reportsTo: "product-agent",
    capabilities: ["verification", "test design", "release confidence"],
    defaultSkillIds: ["unit-test", "integration-test", "bug-analysis"],
  },
  {
    id: "growth-agent",
    role: "growth",
    name: "Growth Agent",
    title: "Growth Agent",
    mission: "Expand go-to-market strategy and pricing decisions.",
    reportsTo: "ceo-agent",
    capabilities: ["marketing strategy", "pricing", "growth planning"],
    defaultSkillIds: ["marketing-strategy", "saas-pricing"],
  },
];
